name: Deploy to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu
          rm -rf app
          git clone https://github.com/mahalakshme-04/devops-portfolio.git app
          cd app
          npm install
          npm run build
          pm2 restart app || pm2 start npm --name "app" -- start
